variables:
  DOCKERHUB: registry.meothantai.com.vn
  DIR: stockproxx

stages:
    - build

build-app-development:
    stage: build    
    only:
    - development
    when: manual
    tags: 
    - vm-builder
    before_script:
    - docker login $DOCKERHUB -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    script:
        - docker build -t $DOCKERHUB/$DIR/stockprowebapp:development -f ./Dockerfile .
        - docker push $DOCKERHUB/$DIR/stockprowebapp:development
        - docker image prune -f

build-app-tags:
    stage: build    
    only:
        - tags 
    tags: 
    - vm-builder
    before_script:
    - docker login $DOCKERHUB -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    script:
        - docker build -t $DOCKERHUB/$DIR/stockprowebapp:$CI_COMMIT_TAG -f ./Dockerfile .
        - docker push $DOCKERHUB/$DIR/stockprowebapp:$CI_COMMIT_TAG
        - docker image prune -f

sonarqube-check:
  image:
    name: registry.meothantai.com.vn/devops/nodejs-scanner:4.6
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: 0
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .sonar/cache
  stage: build
  tags: 
    - vm-builder-docker
  script:
    - >
      sonar-scanner
      -Dsonar.projectName=TerminalStockproWebApp
      -Dsonar.projectKey=TerminalStockproWebApp
      -Dsonar.host.url=${SONAR_HOST_URL}
      -Dsonar.login=${SONAR_TOKEN}
      -Dsonar.sourceEncoding=UTF-8
      -Dsonar.sources=.
      -Dsonar.javascript.node.maxspace=8192
      -Dsonar.qualitygate.wait=true
      -Dsonar.qualitygate.timeout=300
      -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      ${SONAR_PARAMETER}
  allow_failure: true
  only:
    - master 