version: '3.4'

services:
  stockprowebapp:
    container_name: nuxtShop
    image: nuxtShop:1.0.496
    ports:
    - "3030:3000"
    environment:
      - "TZ=Asia/Ho_Chi_Minh"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
