name: Publish image to Docker Hub
on: 
  workflow_dispatch

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t hungleip9/nuxt-shop:latest
      - name: publish
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u hungleip9 --password-stdin
          docker push hungleip9/nuxt-shop:latest
          docker image prune -f