name: Publish image to Docker Hub
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
      - name: Created TAG date for image docker
        run: echo "TAG=$(date +'%d-%m-%Y')" >> $GITHUB_ENV
        run: |
          docker build . -t ${{ secrets.DOCKER_NAME_IMAGE }}:${{ env.TAG }}
      - name: publish
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_NAME_IMAGE }}:${{ env.TAG }}
          docker image prune -f
      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd nuxt-shop-webapp || true
            docker-compose up --build -d
          EOF