name: Publish image to Docker Hub
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t ${{ secrets.DOCKER_NAME_IMAGE }}:latest
      - name: publish
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_NAME_IMAGE }}:latest
          docker image prune -f
      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            docker stop webnode || true
            docker rm webnode || true
            docker pull ${{ secrets.DOCKER_NAME_IMAGE }}:latest
            docker run --name webnode -itd -p 80:3000 ${{ secrets.DOCKER_NAME_IMAGE }}:latest
          EOF