export interface LiveBoardData {
  Commodities: string,
  CompanyName: string,
  FinancialTag: string,
  SectorID: string,
  SubSectorID: string,
  WeightCirculation: number,
  WeightListing: number,
  liveboard: {[key: string]: any};
}
export interface LiveBoardDataSymbol {
  [key: string]: LiveBoardData
}

export interface PriceBoard {
  Symbol: string,
  Open: number,
  Reference: number,
  Close: number,
  High: number,
  Low: number,
  AveragePrice: number,
  Ceiling: number,
  Floor: number,
  MatchVolume: number,
  Change: number,
  ChangePercent: number,
  BidPrice1: string,
  BidVolume1: number,
  BidPrice2: number,
  BidVolume2: number,
  BidPrice3: number,
  BidVolume3: number,
  OfferPrice1: string,
  OfferVolume1: number,
  OfferPrice2: number,
  OfferVolume2: number,
  OfferPrice3: number,
  OfferVolume3: number,
  TotalVolume: number,
  TotalValue: number,
  RemainForeignVolume: number,
  OverBuy: number,
  OverSell: number,
  ForeignBuy: number,
  ForeignBuyValue: number,
  ForeignSell: number,
  ForeignSellValue: number,
  ActiveBuyVol: number,
  ActiveSellVol: number,
  Exchange: string,
  ModifiedDate: Date,
  TimeStamp: number
}
export interface LiveBoardDataTotal {
  Commodities: string,
  CompanyName: string,
  FinancialTag: string,
  SectorID: string,
  SubSectorID: string,
  WeightCirculation: number,
  WeightListing: number,
  Symbol: string,
  Open: number,
  Reference: number,
  Close: number,
  High: number,
  Low: number,
  AveragePrice: number,
  Ceiling: number,
  Floor: number,
  MatchVolume: number,
  Change: number,
  ChangePercent: number,
  BidPrice1: string,
  BidVolume1: number,
  BidPrice2: number,
  BidVolume2: number,
  BidPrice3: number,
  BidVolume3: number,
  OfferPrice1: string,
  OfferVolume1: number,
  OfferPrice2: number,
  OfferVolume2: number,
  OfferPrice3: number,
  OfferVolume3: number,
  TotalVolume: number,
  TotalValue: number,
  RemainForeignVolume: number,
  OverBuy: number,
  OverSell: number,
  ForeignBuy: number,
  ForeignBuyValue: number,
  ForeignSell: number,
  ForeignSellValue: number,
  ActiveBuyVol: number,
  ActiveSellVol: number,
  Exchange: string,
  ModifiedDate: Date,
  TimeStamp: number
}
export interface LiveboardFuture {
  BaseId: string,
  Code: string,
  ExpDate: string,
  Session: string,
  TotalVolume: number,
  TotalValue: number,
  Floor: number,
  Ceiling: number,
  BidPrice1: number,
  BidVolume1: number,
  BidPrice2: number,
  BidVolume2: number,
  BidPrice3: number,
  BidVolume3: number,
  OfferPrice1: number,
  OfferVolume1: number,
  OfferPrice2: number,
  OfferVolume2: number,
  OfferPrice3: number,
  OfferVolume3: number,
  Close: number,
  Reference: number,
  MatchVolume: number,
  Change: number,
  ChangePercent: number,
  High: number,
  Low: number,
  ForeignBuy: number,
  ForeignBuyValue: number,
  ForeignSell: number,
  ForeignSellValue: number,
  TimeStamp: number,
}
export interface LiveboardFutureSymbol {
  [key: string]: LiveboardFuture
}
export interface MarketInfo {
  Symbol: string,
  High: number,
  Low: number,
  Close: number,
  Open: number,
  Average: number,
  Reference: number,
  TotalVolume: number,
  TotalValue: number,
  VolumeMatch: number,
  ValueMatch: number,
  VolumeAgree: number,
  ValueAgree: number,
  Change: number,
  ChangeP: number,
  TotalUp: number,
  TotalNoChange: number,
  TotalDown: number,
  CashFlowUp: number,
  CashFlowDown: number,
  CashFlowNoChange: number,
  VolumeFlowForeign: number,
  ValueFlowForeign: number,
  VolumeForeignBuy: number,
  ValueForeignBuy: number,
  VolumeForeignSell: number,
  ValueForeignSell: number,
  VolumeForeignR: number,
  ValueForeignR: number,
  ModifiedDate: Date | any,
}
export interface DanhSachNhomNganh {
  SubSectorID: string,
  SubSectorName: string,
  SectorX3ID: string,
  SectorX3Name: string,
  SectorX2ID: string,
  SectorX2Name: string,
  SectorID: string,
  SectorName: string
}
export interface TaiKhoanTheoDoi {
  Id: any,
  Name: string,
  CustomerId: number,
  StockCode: string,
  DisplayOrder: number,
  IsDefault: boolean
}
export interface UserInfo {
  Id: number,
  PlanId: number,
  PlanName: string,
  AccountType: string,
  Address: string,
  Avatar: string,
  Status: string,
  ExpirationDate: Date,
  PhoneNumber: string,
  Email: string,
  FullName: string,
  Followers: number,
  Following: number,
  IsBroker: boolean,
  IsActive: boolean
}
export interface NganhCap {
  name: string,
  SectorID: string
}
export interface ChungQuyen {
  Symbol: string,
  Open: number,
  Reference: number,
  Close: number,
  High: number,
  Low: number,
  AveragePrice: number,
  Ceiling: number,
  Floor: number,
  MatchVolume: number,
  Change: number,
  ChangePercent: number,
  BidPrice1: string,
  BidVolume1: number,
  BidPrice2: number,
  BidVolume2: number,
  BidPrice3: number,
  BidVolume3: number,
  OfferPrice1: string,
  OfferVolume1: number,
  OfferPrice2: number,
  OfferVolume2: number,
  OfferPrice3: number,
  OfferVolume3: number,
  TotalVolume: number,
  TotalValue: number,
  RemainForeignVolume: number,
  OverBuy: number,
  OverSell: number,
  ForeignBuy: number,
  ForeignBuyValue: number,
  ForeignSell: number,
  ForeignSellValue: number,
  ActiveBuyVol: number,
  ActiveSellVol: number,
  Exchange: string,
  ModifiedDate: Date,
  TimeStamp: number,
}
export interface MarketHistory{
  VNINDEX: MarketHistoryItem,
  HNXINDEX: MarketHistoryItem,
  VN30: MarketHistoryItem,
  UPINDEX: MarketHistoryItem,
}
export interface MarketHistoryItem {
  c: number[],
  h: number[],
  l: number[],
  o: number[],
  t: number[],
  v: number[],
}
export interface MarketIntradayHistory {
  HNXINDEX: MarketIntradayHistoryItem[],
  HNXUPCOMINDEX: MarketIntradayHistoryItem[],
  VN30: MarketIntradayHistoryItem[],
  VNINDEX: MarketIntradayHistoryItem[],
}
export interface MarketIntradayHistoryItem {
  t: number,
  v: number,
  o: number,
  c: number,
  h: number,
  l: number
}

export interface CompanyIntraday {
  stockCode: string,
  data: CompanyIntradayData[],
}

export interface CompanyIntradayData {
  TimeStamp: number,
  Price: string,
  Volume: string,
  BuySell: string,
  High: number,
  Open: number,
  Low: number,
  TotalValue: number,
  TotalVolume: number,
  Id: string,
  Time: string,
  Change: string,
}

export interface ThiTruong {
  Price: ThiTruongPrice,
  Type: string,
  DisplayOrder: number,
  Id: string,
  Name: string
}
export interface ThiTruongPrice {
  TimeStamp: number,
  High: number,
  Low: number,
  Close: number,
  Volume: number,
  LastTimeStamp: number,
  Change: number,
  ChangePercent: number
}
export interface LichSuHangHoa {
  [key: string]: LichSuHangHoaItem[]
}
export interface LichSuHangHoaItem {
  TimeStamp: number,
  High: number,
  Low: number,
  Open: number,
  Close: number,
  Volume: number,
  LastTimeStamp: number,
  Change: number,
  ChangePercent: number,
}
export interface HangHoa {
  pid: string,
  last_dir: string,
  last_numeric: number,
  last: string,
  bid: string,
  ask: string,
  high: string,
  low: string,
  pc: string,
  pcp: string,
  pc_col: string,
  time: string,
  timestamp:number,
  vol: number,
  matchvol: number,
  cname: string,
  timezone: number,
}
export interface ObjCanhBao {
  [key: string]: ObjCanhBaoItem
}
export interface ObjCanhBaoItem {
  id: string,
  code: string,
  label: string,
  symbol: string,
  time: Date,
  IdDataSaveAlertItem: string,
}
export interface ArrCanhBao {
  id: string,
  code: string,
  label: string,
  symbol: string,
  time: Date,
  IdDataSaveAlertItem: string,
}
export interface DataVuotDinhThungDay {
  Code: string,
  D5: number,
  D20: number,
  D60: number,
  D120: number,
  D240: number,
  All: number
}
export interface DanhSachLocFa {
  Code: string,
  Year: number,
  Quarter: number,
  B: number,
  EPS: number,
  TyLeLaiRong: number,
  TyLeLaiGop: number,
  NoVCSH: number,
  ROA: number,
  ROE: number,
  ROIC: number,
  ROCE: number,
  TangTruongDtQuyGanNhat: number,
  TangTruongDtQuyGanNhi: number,
  TangTruongDtQuyCungKy: number,
  TangTruongDt4Quy: number,
  Ln4Q: number,
  Dt4Q: number,
  TangTruongLnQuyGanNhat: number,
  TangTruongLnQuyGanNhi: number,
  TangTruongLnQuyCungKy: number,
  TangTruongLn4Quy: number,
  DtQuyGanNhat: number,
  DtQuyGanNhi: number,
  LnQuyGanNhat: number,
  LnQuyGanNhi: number,
  S: number
}
export interface DanhSachLocTa {
  Code: string,
  Price1W: number | null,
  Price2W: number | null,
  Price1M: number | null,
  Price3M: number | null,
  Price6M: number | null,
  Price9M: number | null,
  Price1Y: number | null,
  Price2Y: number | null,
  Price3Y: number | null,
  Price5Y: number | null,
  Rsi: number[] | null,
  Macd: number[] | null,
  Signal: number[] | null,
  Mfi: number[] | null,
  Ema5: number[] | null,
  Ema10: number[] | null,
  Ema20: number[] | null,
  Ema50: number[] | null,
  Ema100: number[] | null,
  Ema200: number[] | null,
  Sma5: number[] | null,
  Sma10: number[] | null,
  Sma20: number[] | null,
  Sma50: number[] | null,
  Sma100: number[] | null,
  Sma200: number[] | null,
  Bb: number | null,
  BbUp: number | null,
  BbDown: number | null,
  Beta: number | null,
  BankerRsi: number | null,
  Vol1D: number | null,
  Vol3DTotal: number | null,
  Vol5DTotal: number | null,
  Vol3D: number | null,
  Vol5D: number | null,
  Vol10D: number | null,
  Vol20D: number | null,
  Vol50D: number | null,
  Vol60D: number | null,
  TkCdk1: number | null,
  TkCdk3: number | null,
  TkCdk5: number | null,
  TkCdk3Avg: number | null,
  TkCdk5Avg: number | null,
  Osh: number | null,
  Psh: number | null,
  OshPc: number | null,
  PshPc: number | null,
  Cdk: number | null,
  CdkPc: number | null,
  Shnn: number | null,
  ShnnPc: number | null,
  IchSpan: number[] | null,
  IchSpanA: number[] | null,
  IchSpanB: number[] | null,
  IchKSen: number[] | null,
  IchTSen: number[] | null,
  Price25D: number | null,
  Adx: number | null,
  Mdi: number | null,
  Pdi: number | null,
  SarReversal: boolean[],
  Sar: number[] | null,
}