export interface DataProps {
  IndustryCode: string,
  StockCode: string[],
  Data: {[key: string]: number},
  Id: string,
  Name: string,
  TotalValue: number,
  ChiSo: number,
  VonHoa: number,
  up: number,
  dow: number,
  tc: number,
  ChangePercent: number,
  Day1: number,
  Day5: number,
  Day10: number,
  Day20: number,
  Day60: number,
  Day120: number,
  Day240: number,
  getClass: string,
}